version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.2
  serverless: circleci/serverless-framework@1.0.1

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    parameters:
      target_folder:
        type: string
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false -backend-config="token=${TFE_TOKEN}" << parameters.target_folder >>
            terraform plan << parameters.target_folder >>
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: hashicorp/terraform:light
    parameters:
      target_folder:
        type: string
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve << parameters.target_folder >>
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: circleci/node:lts
    parameters:
      profile:
        type: string
      stage:
        type: string
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            yarn install

      - run:
          name: Serverless Configuration
          command: |
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile default
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" --profile default
            aws configure set region "$AWS_REGION" --profile default

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - run:
          name: chmod permissions
          command: chmod +x .circleci/scripts/deploy.sh

      - run:
          name: Deploy application
          command: |
            source .circleci/scripts/deploy.sh --profile << parameters.profile >>
            serverless deploy -s << parameters.stage >>

workflows:
  version: 2
  deploy_sandbox:
    jobs:
      - plan-apply:
          target_folder: .aws/live/sandbox
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          target_folder: .aws/live/sandbox
          requires:
            - hold-apply
      - deploy:
          profile: arn:aws:iam::838374399476:role/admin
          stage: sandbox
          requires:
            - apply
