version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.2
  serverless: circleci/serverless-framework@1.0.1

jobs:
  sandbox-plan-apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false -backend-config="token=${TFE_TOKEN}" .aws/live/sandbox
            terraform plan .aws/live/sandbox
      - persist_to_workspace:
          root: .
          paths:
            - .

  sandbox-apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve .aws/live/sandbox
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-sanbbox:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            yarn install

      - run:
          name: Serverless Configuration
          command: |
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile default
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" --profile default
            aws configure set region "$AWS_REGION" --profile default

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - run:
          name: chmod permissions
          command: chmod +x .circleci/scripts/deploy.sh

      - run:
          name: Deploy application
          command: .circleci/scripts/deploy.sh serverless deploy -s sandbox

workflows:
  version: 2
  sandbox_plan_approve_apply:
    jobs:
      - sandbox-plan-apply
      - hold-apply:
          type: approval
          requires:
            - sandbox-plan-apply
      - sandbox-apply:
          requires:
            - hold-apply
      - deploy-sanbbox:
          requires:
            - sandbox-apply
