version: 2

jobs:
  sandbox-plan-apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    parameters:
      token:
        type: string
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false -backend-config="token=<< parameters.token >>" .aws/live/sandbox
            terraform plan .aws/live/sandbox
      - persist_to_workspace:
          root: .
          paths:
            - .

  sandbox-apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve .aws/live/sandbox
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  sandbox_plan_approve_apply:
    jobs:
      - sandbox-plan-apply:
          token: $TFE_TOKEN
      - hold-apply:
          type: approval
          requires:
            - sandbox-plan-apply
      - sandbox-apply:
          requires:
            - hold-apply
